version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./volumes/mongodb:/data/db

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    depends_on:
      - mongodb
    restart: always
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    links:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/pritunl?authSource=admin
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./volumes/pritunl:/etc/pritunl
    ports:
      - "80:80"
      - "443:443"
      - "1194:1194/udp"
      - "1194:1194/tcp"
